name: notes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.2"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  auto_size_text: ^3.0.0
  sqflite: ^2.0.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.8
  path_provider: ^2.0.8
  fluttertoast: ^8.0.9
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
